createUser field: accepted_privacy_policy: true -> create user
ToKoSoftware/dhbw-svm-portal pull request #163
Opened 2021-02-12 09:53 UTC by LisaFremdt

2021-02-12 11:13 UTC, DominikRuf requested changes

2021-02-12 11:13 UTC, DominikRuf commented on server/src/api/v1/users/create-user.ts
> +    if(accepted_privacy_policy !== true) {
schöner:
```suggestion
    if(!accepted_privacy_policy) {
```

2021-02-12 11:13 UTC, DominikRuf commented on server/src/api/v2/organizations/get-organization-by-access_code.ts
> +        .scope([Vars.currentUserIsAdmin ? 'full' : 'active']) //  todo permission check in #98
todo permission check?
Bitte gleich machen!

2021-02-12 11:13 UTC, DominikRuf commented on server/src/api/v2/organizations/get-organization-by-access_code.ts
> +            }: {}
mMn nicht nötig.
Was meinst du @TomasKostadinov ?
Effektiv brauchen wir ja nur die Org und sonst nichts.

2021-02-12 11:13 UTC, DominikRuf commented on server/src/interfaces/users.interface.ts
> +
```suggestion
```

2021-02-12 11:13 UTC, DominikRuf commented on server/src/server.ts
> +    app.get('/api/v2/access/:code', userIsAuthorized, (req, res) => getOrganizationByAccessCode(req, res));
```suggestion
    app.get('/api/v2/access/:code', (req, res) => getOrganizationByAccessCode(req, res));
```
userIsAuthorized macht an der Stelle keinen Sinn, da sich der User ja grade erst registrieren will!

2021-02-12 11:13 UTC, DominikRuf commented on server/src/server.ts
> +
```suggestion
```

2021-02-12 11:13 UTC, DominikRuf commented on server/src/server.ts
> +
```suggestion
```

2021-02-12 11:13 UTC, DominikRuf commented on server/src/api/v1/users/create-user.ts
> +import { Vars } from '../../../vars';
unnötiger Import, oder?

2021-02-12 11:14 UTC, TomasKostadinov commented on server/src/api/v2/organizations/get-organization-by-access_code.ts
> +            }: {}
Ja org sonst nichts

2021-02-12 11:14 UTC, DominikRuf commented on server/src/api/v2/organizations/get-organization-by-access_code.ts
> +        .scope([Vars.currentUserIsAdmin ? 'full' : 'active']) //  todo permission check in #98
Grade erst gekommen:
currentUser existiert hier garnicht! Bitte einfach blank die Org ausliefern. ('active' scope kann bestehen bleiben)

2021-02-12 15:17 UTC, DominikRuf requested changes

2021-02-12 15:17 UTC, DominikRuf commented on server/src/api/v1/users/create-user.ts
> +import { Vars } from '../../../vars';
Warum resolved? Ist immer noch unnötiger Import!

2021-02-12 19:15 UTC, DominikRuf commented
Mir ist grade noch beim Testen eine Sache noch aufgefallen:
Wenn man keinen access_code eingibt, dann joined man auch keiner org und muss daraus folgend keine policy accepted werden.

2021-02-14 12:00 UTC, TomasKostadinov approved these changes

2021-02-14 12:00 UTC, DominikRuf approved these changes

2021-02-14 12:00 UTC, merged