Backend: DirectDebitMandate
ToKoSoftware/dhbw-svm-portal pull request #164
Opened 2021-02-13 11:03 UTC by DominikRuf

Closes: #36

2021-02-13 13:51 UTC, TomasKostadinov requested changes

2021-02-13 13:51 UTC, TomasKostadinov commented on server/src/models/organization.model.ts
> +    CI: string; // "Gläubiger-Identifikationsnummer"
Bitte etwas sprechenderes Finden als `CI` z.B. Creditor_Id

2021-02-13 13:51 UTC, TomasKostadinov commented on server/src/api/v2/direct-debit-mandate/delete-direct-debit-mandate.ts
> +export async function deleteDirectDebitMandate(req: Request, res: Response): Promise<Response> {
Ein Gedanke dazu: Hier sollten soft deletes mit gekündigt am über das deletedAt Feld (Sequelize paranoid Modus) verwendet werden
-> Dann kann nachvollzogen werden, wann das widerrufen wurde

2021-02-13 22:03 UTC, DominikRuf commented on server/src/api/v2/direct-debit-mandate/delete-direct-debit-mandate.ts
> +export async function deleteDirectDebitMandate(req: Request, res: Response): Promise<Response> {
Done

2021-02-14 10:04 UTC, TomasKostadinov requested changes

2021-02-14 10:04 UTC, TomasKostadinov commented on server/src/server.ts
> +    app.delete('/api/v2/directDebitMandate', userIsAuthorized, (req, res) => deleteDirectDebitMandate(req, res));
Urls immer plural, und kebab-case

```suggestion
    app.get('/api/v2/direct-debit-mandates', userIsAuthorized, (req, res) => getDirectDebitMandate(req, res));
    app.get('/api/v2/direct-debit-mandates', userIsAuthorized, userIsAdmin, (req, res) => getDirectDebitMandates(req, res));
    app.post('/api/v2/direct-debit-mandates', userIsAuthorized, (req, res) => createDirectDebitMandate(req, res));
    app.delete('/api/v2/direct-debit-mandates', userIsAuthorized, (req, res) => deleteDirectDebitMandate(req, res));
```

Um jetzt in z. 190 noch unterscheiden zu können, was was ist bitte das unter den user hängen 

/api/v2/users/:id/direct-debit-mandates
Dann muss man auch nicht per body das mitsenden

2021-02-14 10:16 UTC, TomasKostadinov approved these changes

2021-02-14 10:16 UTC, merged