Added previous meeting protocols
ToKoSoftware/dhbw-svm-portal pull request #19
Opened 2021-01-05 13:38 UTC by BlueEnni

2021-01-08 09:17 UTC, TomasKostadinov commented
@BlueEnni was ist der Status hier?

2021-01-09 22:20 UTC, TomasKostadinov requested changes
Bitte die Dateien als .md speichern

2021-01-10 10:51 UTC, BlueEnni commented
> Bitte die Dateien als .md speichern

done

2021-01-10 11:31 UTC, TomasKostadinov approved these changes

2021-01-10 11:31 UTC, merged