Backend: Teams read api
ToKoSoftware/dhbw-svm-portal pull request #61
Opened 2021-01-14 18:47 UTC by DominikRuf

closes: #42

2021-01-14 18:48 UTC, DominikRuf commented
Nach #59

2021-01-15 08:09 UTC, TomasKostadinov requested changes

2021-01-15 08:09 UTC, TomasKostadinov commented on server/src/api/v2/teams/get-teams.ts
> +    if (!currentUserIsAdminOrMatchesId(req.params.id)) {
Die id ist doch die Team ID und nicht die user id, oder?

2021-01-15 10:24 UTC, TomasKostadinov requested changes

2021-01-15 10:24 UTC, TomasKostadinov commented on server/src/api/v2/teams/get-teams.ts
> +    Vars.loggy.log(Vars.currentUser);
```suggestion
```

2021-01-15 10:24 UTC, TomasKostadinov commented on server/src/api/v2/teams/get-teams.ts
> +            ... Vars.currentUser.is_admin ? {
nice :D

2021-01-15 10:24 UTC, TomasKostadinov commented on server/src/models/user.model.ts
> +    openData: {
```suggestion
    publicData: {
```

2021-01-15 10:24 UTC, TomasKostadinov commented on server/src/api/v2/teams/get-teams.ts
> +                    model: User.scope('openData')
```suggestion
                    model: User.scope('publicData')
```

2021-01-15 10:30 UTC, TomasKostadinov approved these changes

2021-01-15 10:31 UTC, merged