ADD:meeting protocol 2021-01-14
ToKoSoftware/dhbw-svm-portal pull request #64
Opened 2021-01-14 22:09 UTC by BlueEnni

Please check the 'Demodata' & the 'To-Do' section - I may have missed some information on those two parts

2021-01-14 22:19 UTC, DominikRuf requested changes
Kleinigkeit, die ich anders schreiben würde. Sonst top Mitschrieb, Danke! :+1:

2021-01-14 22:19 UTC, DominikRuf commented on documentation/meetings/2021-01-14.md
> +    ○ Route hat jetzt einen Scope
```suggestion
    ○ Jedes Model hat jetzt einen DefaultScope und verschiedene passende Scopes
```

2021-01-14 22:23 UTC, DominikRuf requested changes

2021-01-14 22:23 UTC, DominikRuf commented on documentation/meetings/2021-01-14.md
> +		  + rolle, team, membership (member & team …)
```suggestion
		  + organization, user, role, team, membership (user & team), roleAssignment (user & role)
```

2021-01-15 11:10 UTC, BlueEnni commented
Thx @DominikRuf  - added your suggestions

2021-01-16 10:25 UTC, DominikRuf approved these changes

2021-01-16 10:25 UTC, merged