Create Events in Frontend
ToKoSoftware/dhbw-svm-portal pull request #99
Opened 2021-01-26 11:34 UTC by TomasKostadinov

2021-02-01 16:36 UTC, TomasKostadinov commented
Bitte mal reviewen und reinmengen :) 
Es funktioniert alles und nichts.

2021-02-02 19:42 UTC, DominikRuf commented
![image](https://user-images.githubusercontent.com/56634563/106653402-0c8d8380-6597-11eb-9c2d-0915a1858567.png)
in Events wird immer die aktuelle Uhrzeit (wann der letzte reload der seite war) angezeigt und nicht die aus der DB

2021-02-02 20:50 UTC, DominikRuf requested changes

2021-02-02 20:50 UTC, DominikRuf commented on frontend/src/app/edit-create-pages/create-event/create-event.component.html
> +      ></app-datetime-input>
formControlName und label passt nicht zueinander

2021-02-02 20:50 UTC, DominikRuf commented on frontend/src/app/edit-create-pages/create-poll/create-poll.component.ts
> +        answer_team_id: ['bbbbbbbb-ed27-4c69-8e45-77416965091f'],
absicht, dass das da hard-coded ist?

2021-02-02 20:50 UTC, DominikRuf commented on frontend/src/app/edit-create-pages/create-role/create-role.component.html
> +      </app-input>
Copy pasta ;)

2021-02-02 20:50 UTC, DominikRuf commented on frontend/src/app/edit-create-pages/edit-event/edit-event.component.html
> +      ></app-datetime-input>
Same wie in create event

2021-02-02 20:50 UTC, DominikRuf commented on frontend/src/app/edit-create-pages/edit-role/edit-role.component.html
> +      <div class="flex justify-end w-full">
copy pasta

2021-02-03 08:57 UTC, DominikRuf approved these changes

2021-02-03 10:20 UTC, merged